env:
  browser: true
  es6: true
  jest: true
extends:
  - airbnb
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/state-in-constructor: 0
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error

  settings:
    import/resolver:
      webpack:
        config: ./config/webpack.dev.js
      babel-module:
        root: ./src
