name: Yarn CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.0.0
    - name: yarn install, build, and test
      run: |
        sudo yarn install

        yarn eslint | tee eslint_output.txt

        if [ -z $(grep -E "[1-9]\d* error" ./eslint_output.txt) ]; then
          echo "No errors "
          exit 0
        else
          echo "Please correct the errors."
          exit 1
        fi

      env:
        CI: true
